MODEL:
  META_ARCHITECTURE: "EntityFPNRLE"
  MASK_ON: True
  BACKBONE:
    NAME: "build_retinanet_swin_fpn_backbone"
    FREEZE_AT: -1
  SWINT:
    EMBED_DIM: 96
    PATCH_SIZE: 4
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.2
    APE: False
  WEIGHTS: "/group/20018/gavinqi/pretrained_model/pretrained_model/ft_local/swin_tiny_patch4_window7_224_trans.pth"
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    TOP_LEVELS: 2
  FCOS:
    NUM_CLASSES: 1
  CONDINST:
    CLASS_AGNOSTIC: True
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: False
      IN_FEATURES: ["p3", "p4", "p5"]
    MASK_HEAD:
      CLUSTER_WEIGHT: 0.5
      DYNAMIC: ["111", "110", "101", "100", "011", "010", "001"]
      DYNAMIC_WEIGHT: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25]
DATASETS:
  TRAIN: ("coco_2017_train_entity_rle",)
  TEST: ("coco_2017_val_entity_rle",)
SOLVER:
  OPTIMIZER: "adamw"
  CHECKPOINT_PERIOD: 40000
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  STEPS: (180000, 250000)
  MAX_ITER: 270000
  WARMUP_ITERS: 1500
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
INPUT:
  MASK_FORMAT: "bitmask"
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
VERSION: 2